# Generated by Django 4.2.29 on 2026-07-07 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('shop_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='vendors/banners/')),
                ('business_type', models.CharField(choices=[('individual', 'Individual / Sole Proprietor'), ('partnership', 'Partnership'), ('private_limited', 'Private Limited Company'), ('public_limited', 'Public Limited Company')], default='individual', max_length=20)),
                ('gstin', models.CharField(blank=True, help_text='15-character GST Identification Number', max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('business_phone', models.CharField(max_length=15)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage per sale', max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
