# Generated by Django 4.2.29 on 2026-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_cart',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_session_cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
