# Generated by Django 4.2.29 on 2026-07-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_role_vendorprofile'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission in rupees', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission % applied at time of order', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who sold this item. Null for platform products.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='accounts.vendorprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_payout',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be paid to vendor after commission', max_digits=10),
        ),
    ]
