# Generated by Django 4.2.29 on 2026-07-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_role_vendorprofile'),
        ('products', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Leave blank for platform-owned products', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.vendorprofile'),
        ),
    ]
